mod home;
pub use home::Home;
mod log_exercise;
pub use log_exercise::LogExercise;
mod log_cardio;
pub use log_cardio::LogCardio;
mod history;
pub use history::History;
mod start_workout;
pub use start_workout::StartWorkout;
mod navbar;
pub use navbar::Navbar;
mod records;
pub use records::Records;
pub mod format;
mod bodyweight;
pub use bodyweight::BodyWeight;
mod progress;
pub use progress::Progress;
mod manage_templates;
pub use manage_templates::ManageTemplates;